name: TEST
on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
            go-version-file: './go.mod'
            cache-dependency-path: "**/*.sum"
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v -cover ./... 